### ISSUE TITLE
[ci] SHA3 captures seem to be broken/flaky in CI

### ISSUE THREAD

**Issue by vogelpi** [lowRISC/ot-sca#283]
I've observed that in very many cases, CI captures for SHA3 don't work. We should investigate what is going on an fix it.

**Comment by nasahlpa** [comment]
Yes, I noticed this too for the uJSON version of SHA3. The reason for that is mostly that we wait for an [ACK ](https://github.com/lowRISC/ot-sca/blob/cb90c9c9f6cbd74bafc5818bd6fc8e289fb5336e/capture/lib/ot_communication.py#L427)from OT after sending command from ot-sca.

I am not sure why we introduced this in `simpleserial`? For AES this is also not needed? Maybe @m-temp or @vrozic know more?

**Comment by m-temp** [comment]
I don't know what's happening in the CI, but for SHA3 (and KMAC) we had a lot of synchronization issues. Unfortunately, they were never really resolved, but sleeps and acks were added until it worked... The underlying problem is, that simple serial has no real bidirectional handshaking. In contrast to AES SHA3 and KMAC operations take also longer. This might increase the effect.
